### ISSUE TITLE
[nanbield] Is `usrmerge` DISTRO_FEATURE now required for `udev` (eudev)?

### ISSUE THREAD

**Issue by moto-timo** [meta-homeassistant/meta-homeassistant#103]
`2024-01-18 18:41:00 - ERROR    - Command "/home/runner/work/meta-homeassistant/meta-homeassistant/build$ /home/runner/work/meta-homeassistant/meta-homeassistant/poky/bitbake/bin/bitbake -c build core-image-homeassistant" failed
--- Error summary ---
ERROR: Nothing RPROVIDES 'udev' (but /home/runner/work/meta-homeassistant/meta-homeassistant/build/../poky/meta/recipes-core/packagegroups/packagegroup-core-boot.bb RDEPENDS on or otherwise requires it)
systemd RPROVIDES udev but was skipped: missing required distro feature 'usrmerge' (not in DISTRO_FEATURES)
eudev RPROVIDES udev but was skipped: conflicting distro feature 'systemd' (in DISTRO_FEATURES)
ERROR: Required build target 'core-image-homeassistant' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-homeassistant', 'packagegroup-core-boot', 'udev']`

https://github.com/moto-timo/meta-homeassistant/actions/runs/7574509854/job/20629038310

**Comment by Gerry546** [comment]
Essentially yes, it is now a required feature if you want to have systemd in your distro: [link](https://docs.yoctoproject.org/migration-guides/migration-4.3.html#systemd-changes)
