### ISSUE TITLE
RDEPENDS

### ISSUE THREAD

**Issue by Kujoo25** [meta-homeassistant/meta-homeassistant#37]
Hi,
I'm having problem with dependencies in ha recipe.
In recipe ha have dependency:
${PYTHON_PN}-attrs (>=19.1.0) \

and in newest meta-python layers:
zeus: python-attrs - 19.2.0,
master: python-attrs - 19.3.0

everything is ok by the time you run it, then I have this error:
pkg_resources.DistributionNotFound: The 'attrs==19.1.0' distribution was not found and is required by homeassistant
so, that means ha requires python-attrs version equal 19.1.0, but layers have newer versions.

I see that now ha layer is only compatybile with warrior branch.
So meta-homeassistant require downgrade to warrior branch (meta-python)?

Regards

**Comment by bachp** [comment]
Hi

Home assistant has some checks at runtime where they are very picky what exact version it wants.

One possible solution would be to take the coresponding version from meta-python and put it in here so it machtes wich what home assistant requires.

**Comment by agherzan** [comment]
@Kujoo25 use the `dunfell` branch in conjunction with the relevant dependencies (check-out readme).
