### ISSUE TITLE
RE: [LOOKING FOR MAINTAINERS]: From Potential Maintainer

### ISSUE THREAD

**Issue by NGenetzky** [meta-homeassistant/meta-homeassistant#41]
> [LOOKING FOR MAINTAINERS] 

Hello, I am Nathan G and I was considering helping with this project. I am curious about what your expectations would be of a maintainer? Is there a user base that has certain expectations?

**Comment by bachp** [comment]
@NGenetzky My original goal was to keep the layer up to date with the latest home assistant and current yocto releases.

 The main reason I'm looking for a new maintainer is that I don't use home assistant anymore via yocto. So it's hard for me to verify that things still work. Somebody who is using it would be suited way better. Other than that I don't know what the expectation of other users are.

**Comment by mboyar** [comment]
Hello guys,

I have some yocto experience in the professional projects. And also I've recoreded a training series on yocto in youtube.com/doctorpi. Just tell me the starting point, such as you can open an issue, and assign to me

**Comment by bachp** [comment]
Hi @mboyar The main issue is keeping the recipe up to date with the releases of home-assistant. I tried to do it for several releases but it was a lot of work, which I currently can't invest.

It might be worth to invest into automating the update process similar to what's done in [nixpkgs](https://github.com/NixOS/nixpkgs/tree/master/pkgs/servers/home-assistant).
