### ISSUE TITLE
Quick Start instructions fail to build

### ISSUE THREAD

**Issue by mkilivan** [meta-homeassistant/meta-homeassistant#43]
### Reproduce the issue
Follow the quick start instructions.

### Expected result
Should successfully build the image. 

### Result
I got the following error.
```
ERROR: Layer homeassistant is not compatible with the core layer which only supports these series: gatesgarth (layer is compatible with warrior zeus)
```
### Notes
Note that the quick start instructions check out the HEAD of the master branch. The current version of the openembedded layer is `gatesgarth` and as the error message states meta-homeassistant is not compatible with this version. See conf/layer.conf file
```
LAYERSERIES_COMPAT_homeassistant = "warrior zeus"
```

I have manually switched to the `zeus` branch and I got this error this time:
```
Parsing recipes: 100% |########################################################################################################################################| Time: 0:01:13
Parsing of 2411 .bb files complete (0 cached, 2411 parsed). 3600 targets, 119 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'python3-xmltodict' (but /git/home-assistant/openembedded-core/meta-homeassistant/recipes-homeassistant/homeassistant/python3-homeassistan
t_0.107.6.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-xmltodict' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-xmltodict']
NOTE: Runtime target 'python3-homeassistant' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-homeassistant', 'python3-xmltodict']
ERROR: Required build target 'core-image-homeassistant' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-homeassistant', 'python3-homeassistant', 'python3-xmltodict']
```
### Workaround/Fix
Master branch of meta-homeassistant doesn't seem to be compatible with the older version of the core layer any more. But it successfully builds when `gatesgarth` was added to compatible layers list in conf/layer.conf. 

```
LAYERSERIES_COMPAT_homeassistant = "gatesgarth"
```
**Note** I haven't tried using the dunfell branch.

**Comment by bachp** [comment]
@mkilivan Could you create a PR with the fixes you propose?

**Comment by mkilivan** [comment]
@bachp It seems the CI build failed because the free space was running low. Is this something you can fix?

**Comment by bachp** [comment]
@mkilivan I need to take a look. But I'm afraid it seems Github Actions is not really suitable to run OE builds.
