### ISSUE TITLE
[RFC] Dunfell support

### ISSUE THREAD

**Issue by agherzan** [meta-homeassistant/meta-homeassistant#46]
There is no current dunfell support for `meta-homeassistant` and the build won't succeed as multiple dependencies are not in place on the respective _dunfell_ `meta-oe` branch (only in later revisions). The `dunfell` is an LTS version so supporting it would make sense as more products will tend to gravitate around this version.

Proposal: introduce the _dunfell_ branch in `meta-homeassistant` that backports or introduces all the dependencies/functionality not available in the _dunfell_ branches of the dependencies. eg. pytthon modules available in `meta-python`>_dunfell_ but not in the _dunfell_ branch.

I am available to push such work if the maintainers are willing to fork the current master as a _dunfell_ branch.

**Comment by bachp** [comment]
@agherzan I'm open for this. However I won't be able to maintain this. If you step up to do the work I'm more than happy to add you as a maintainer to the project.

**Comment by agherzan** [comment]
When you say `this`, you mean the _dunfell_ branch, right?

**Comment by bachp** [comment]
To be honest I'm not actively updating the master branch either atm. So by this I mean primarly the dunfell branch, but I would probably make it the default branch until somebody steps up to maintain the master branch too.

**Comment by agherzan** [comment]
Hello @bachp. Thanks for clarifying. I gave this a second thought and I think the way forward would be to maintain the dependent python modules as a separate layer. This would increase reusability on other projects.. So I propose to create a _dunfell_ branch and just reference this layer as a dependency in the readme of the _dunfell_ branch. What do you think? Again, if you create the _dunfell_ branch I will contribute the patches. I can't though guarantee maintainership but I'll definitely contribute as much as possible.

**Comment by bachp** [comment]
@agherzan In the begining I tried to add all dependencies to [meta-python](https://github.com/openembedded/meta-openembedded/tree/master/meta-python) but keeping up with home assistant updates is already hard as it often requires specific versions. It is even harder if you have to go via meta-python.

There was also discussion with @moto-timo to add homeassistant to meta-python. But this never happened.

Anyway I created the dunfell branch.

**Comment by agherzan** [comment]
Can you give me an example of a specific version issue? Does meta-python only include older versions or do you actually need very specific versions to be concurrently supported?

**Comment by bachp** [comment]
I don't have a specific example. There are two cases I hit:

1. meta-python has a newer version but home assistant is not allowing this new version => Keep the older version in meta-homassistant
2. home assistant needs a newer version than what is in meta-python => Add new version to meta-homeassistant, submit the update to meta-python and then remove it again from meta-homeassistant once it landed in meta-python

**Comment by agherzan** [comment]
That's what I was expecting indeed. Ok. Let's maintain the same approach for dunfell too on the currently supported HA version.
