### ISSUE TITLE
Update home-assistant recipe to latest version (2022.x)

### ISSUE THREAD

**Issue by bachp** [meta-homeassistant/meta-homeassistant#59]
Currently the layer contains an almost 4 year old version of home assistant. Update to the latest version considering only the minimal dependencies in this first step.

**Comment by Stefan-Schmidt** [comment]
I am looking into this right now. Home Assistant core 2022.5.1 plus its new and updated dependencies. Will keep you updated.

**Comment by Stefan-Schmidt** [comment]
@bachp Have a look at my draft PR when you have time and let me know if that goes in the direction you are aiming at.
