### ISSUE TITLE
meta-python-mixin URL change?

### ISSUE THREAD

**Issue by RobertBerger** [meta-homeassistant/meta-homeassistant#61]
`git clone https://booting.oniroproject.org/distro/meta-python-mixin.git` does not seem to exist anymore.

Should it be `https://gitlab.eclipse.org/eclipse/oniro-core/meta-python-mixin` instead?

**Comment by bachp** [comment]
Hm I think this can be remove entirely, at leat for the kirkstone branch. The mixin branch was only needed for dunfell.

@RobertBerger Are you using dunfell or kirkstone?

**Comment by RobertBerger** [comment]
I will try it on `langdale`, which was just released.

**Comment by bachp** [comment]
I think you can definitely skip it there.

**Comment by RobertBerger** [comment]
Thanks. I will give it a try and keep you updated.

**Comment by Gerry546** [comment]
Currently, the project support the use of `mickledore` and indeed does no longer need this layer. Therefore I would consider this issue closed.
