### ISSUE TITLE
python3-ha-av_10.0.0.bb:do_compile  Failure

### ISSUE THREAD

**Issue by reiwaembedded** [meta-homeassistant/meta-homeassistant#86]
Hello,

I am building homeassistant with Yocto and everything compiles successfully apart from the python3-ha-av_10.0.0.
This appears to be an issue even for those installing the package manually as discussed and solved here: https://community.home-assistant.io/t/unable-to-install-package-ha-av/466286/31

I am using the Mickledore branch.
Has anyone successfully built this recently? and how can I solve this issue? The rest of the build has completed successfully.
Thanks

**Comment by Gerry546** [comment]
Hi,

Yeah I built it recently and I haven't had any problems with building or running it.

Could you tell me a bit more, what error message are you exactly seeing?

One thing to note is that this package depends on [ffmpeg](https://github.com/yoctoproject/poky/blob/master/meta/recipes-multimedia/ffmpeg/ffmpeg_6.0.bb) which does complain about having to accept licenses depending on how this is build exactly.

**Comment by reiwaembedded** [comment]
Thanks for the response @ Gerry546. I did not get any warnings or errors regarding ffmpeg.
Below is the error log with regard to the python3-ha-av:

<pre>Initialising tasks: 100% |#####################################################################################################| Time: 0:00:10
Sstate summary: Wanted 354 Local 341 Mirrors 0 Missed 13 Current 4371 (96% match, 99% complete)
<b>NOTE</b>: Executing Tasks
<font color="#C01C28"><b>ERROR</b></font>: <font color="#C01C28">python3-ha-av-10.0.0-r0 do_compile: ExecutionError(&apos;/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/temp/run.do_compile.32763&apos;, 1, None, None)</font>
<font color="#C01C28"><b>ERROR</b></font>: <font color="#C01C28">Logfile of failure stored in: /home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/temp/log.do_compile.32763</font>
Log data follows:
| DEBUG: Executing shell function do_compile
| * Getting build dependencies for wheel...
| running egg_info
| writing ha_av.egg-info/PKG-INFO
| writing dependency_links to ha_av.egg-info/dependency_links.txt
| writing entry points to ha_av.egg-info/entry_points.txt
| writing top-level names to ha_av.egg-info/top_level.txt
| reading manifest file &apos;ha_av.egg-info/SOURCES.txt&apos;
| reading manifest template &apos;MANIFEST.in&apos;
| warning: no files found matching &apos;*.h&apos; under directory &apos;include&apos;
| adding license file &apos;LICENSE.txt&apos;
| writing manifest file &apos;ha_av.egg-info/SOURCES.txt&apos;
| * Building wheel...
| running bdist_wheel
| running build
| running build_py
| running build_ext
| building &apos;av.codec.codec&apos; extension
| x86_64-poky-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot -Wsign-compare -DNDEBUG -g -O3 -Wall -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map -fmacro-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3/3.11.4/Python-3.11.4=/usr/src/debug/python3/3.11.4-r0 -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3/3.11.4/Python-3.11.4=/usr/src/debug/python3/3.11.4-r0 -fmacro-prefix-map=/build/path/unavailable/=/usr/src/debug/python3/3.11.4-r0 -fdebug-prefix-map=/build/path/unavailable/=/usr/src/debug/python3/3.11.4-r0 -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot= -fmacro-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot= -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot-native= -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map -fmacro-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3/3.11.4/Python-3.11.4=/usr/src/debug/python3/3.11.4-r0 -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3/3.11.4/Python-3.11.4=/usr/src/debug/python3/3.11.4-r0 -fmacro-prefix-map=/build/path/unavailable/=/usr/src/debug/python3/3.11.4-r0 -fdebug-prefix-map=/build/path/unavailable/=/usr/src/debug/python3/3.11.4-r0 -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot= -fmacro-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot= -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot-native= -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map -fmacro-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/ha-av-10.0.0=/usr/src/debug/python3-ha-av/10.0.0-r0 -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/ha-av-10.0.0=/usr/src/debug/python3-ha-av/10.0.0-r0 -fmacro-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/ha-av-10.0.0=/usr/src/debug/python3-ha-av/10.0.0-r0 -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/ha-av-10.0.0=/usr/src/debug/python3-ha-av/10.0.0-r0 -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot= -fmacro-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot= -fdebug-prefix-map=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot-native= -fPIC -I/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot/usr/include/python3.11 -c src/av/codec/codec.c -o build/temp.linux-x86_64-cpython-311/src/av/codec/codec.o
| src/av/codec/codec.c: In function &apos;__pyx_pymod_exec_codec&apos;:
| src/av/codec/codec.c:5977:36: error: &apos;AV_CODEC_CAP_TRUNCATED&apos; undeclared (first use in this function); did you mean &apos;AV_CODEC_CAP_HARDWARE&apos;?
|  5977 |   __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_TRUNCATED); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 55, __pyx_L1_error)
|       |                                    ^~~~~~~~~~~~~~~~~~~~~~
|       |                                    AV_CODEC_CAP_HARDWARE
| src/av/codec/codec.c:5977:36: note: each undeclared identifier is reported only once for each function it appears in
| src/av/codec/codec.c:6163:36: error: &apos;AV_CODEC_CAP_AUTO_THREADS&apos; undeclared (first use in this function); did you mean &apos;AV_CODEC_CAP_SLICE_THREADS&apos;?
|  6163 |   __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_AUTO_THREADS); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 105, __pyx_L1_error)
|       |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                    AV_CODEC_CAP_SLICE_THREADS
| src/av/codec/codec.c:6226:36: error: &apos;AV_CODEC_CAP_INTRA_ONLY&apos; undeclared (first use in this function); did you mean &apos;AV_CODEC_PROP_INTRA_ONLY&apos;?
|  6226 |   __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_INTRA_ONLY); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 117, __pyx_L1_error)
|       |                                    ^~~~~~~~~~~~~~~~~~~~~~~
|       |                                    AV_CODEC_PROP_INTRA_ONLY
| src/av/codec/codec.c:6247:36: error: &apos;AV_CODEC_CAP_LOSSLESS&apos; undeclared (first use in this function); did you mean &apos;AV_CODEC_PROP_LOSSLESS&apos;?
|  6247 |   __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_LOSSLESS); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 119, __pyx_L1_error)
|       |                                    ^~~~~~~~~~~~~~~~~~~~~
|       |                                    AV_CODEC_PROP_LOSSLESS
| error: command &apos;/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/core2-64-poky-linux/python3-ha-av/10.0.0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/x86_64-poky-linux-gcc&apos; failed with exit code 1
| 
| ERROR Backend subprocess exited when trying to invoke build_wheel
| WARNING: exit code 1 from a shell command.
<font color="#C01C28"><b>ERROR</b></font>: <font color="#C01C28">Task (/home/tower1/yocto/mickledore/poky/meta-homeassistant/recipes-homeassistant/homeassistant-component-deps/python3-ha-av_10.0.0.bb:do_compile) failed with exit code &apos;1&apos;</font>
<b>NOTE</b>: Tasks Summary: Attempted 10019 tasks of which 10016 didn&apos;t need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/tower1/yocto/mickledore/poky/meta-homeassistant/recipes-homeassistant/homeassistant-component-deps/python3-ha-av_10.0.0.bb:do_compile
Summary: There was 1 ERROR message, returning a non-zero exit code.</pre>

**Comment by Gerry546** [comment]
Hmm at first I though it might have something to do with the machine you are building for since I build mostly arm images and not for x86-64. But I cannot seem to reproduce the problem, neither with cleaning my downloads and sstate, or building the same machine.

So this also happens when you clean out all cache information about the recipe and just build this one?

**Comment by reiwaembedded** [comment]
It's failing even after cleaning all the cache using cleanall both for the recipe and the entire image.

I have so far tried to compile for the following machines, but the recipe is failing with the same error(s):
qemux86-64
qemux86
qemuarm

The ffmpeg recipe being built is ffmpeg_6.0.bb.

I hope I can get some solution to this.

**Comment by reiwaembedded** [comment]
I have tried building for raspberrypi-cm3 and I now get the following error. I am not sure if it is related to the above recipe but so far I have not managed to build the homeassistant regardless of the target machine. Could it be an issue with my host machine?

<pre>Initialising tasks: 100% |#####################################################################################################| Time: 0:00:56
Sstate summary: Wanted 362 Local 346 Mirrors 0 Missed 16 Current 4244 (95% match, 99% complete)
<b>NOTE</b>: Executing Tasks
<font color="#C01C28"><b>ERROR</b></font>: <font color="#C01C28">core-image-homeassistant-1.0-r0 do_rootfs: Could not invoke dnf. Command &apos;/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/recipe-sysroot-native/usr/bin/dnf -v --rpmverbosity=info -y -c /home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/rootfs/etc/dnf/dnf.conf --setopt=reposdir=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/rootfs/etc/yum.repos.d --installroot=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/rootfs --setopt=logdir=/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/temp --repofrompath=oe-repo,/home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/oe-rootfs-repo --nogpgcheck install packagegroup-core-boot python3-homeassistant run-postinsts&apos; returned 1:</font>
<font color="#C01C28">DNF version: 4.16.1</font>
<font color="#C01C28">cachedir: /home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/rootfs/var/cache/dnf</font>
<font color="#C01C28">Added oe-repo repo from /home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/oe-rootfs-repo</font>
<font color="#C01C28">User-Agent: falling back to &apos;libdnf&apos;: could not detect OS or basearch</font>
<font color="#C01C28">repo: using cache for: oe-repo</font>
<font color="#C01C28">oe-repo: using metadata from Fri 01 Sep 2023 04:17:50 AM UTC.</font>
<font color="#C01C28">Last metadata expiration check: 0:00:02 ago on Fri 01 Sep 2023 04:17:53 AM UTC.</font>
<font color="#C01C28">--&gt; Starting dependency resolution</font>
<font color="#C01C28">--&gt; Finished dependency resolution</font>
<font color="#C01C28">Error: </font>
<font color="#C01C28"> Problem: conflicting requests</font>
<font color="#C01C28">  - nothing provides python3-async-timeout = 4.0.2 needed by python3-homeassistant-2023.5.0-r0.cortexa7t2hf_neon_vfpv4 from oe-repo</font>
<font color="#C01C28">  - nothing provides python3-attrs = 22.2.0 needed by python3-homeassistant-2023.5.0-r0.cortexa7t2hf_neon_vfpv4 from oe-repo</font>
<font color="#C01C28">  - nothing provides python3-pyyaml = 6.0 needed by python3-homeassistant-2023.5.0-r0.cortexa7t2hf_neon_vfpv4 from oe-repo</font>
<font color="#C01C28">  - nothing provides python3-aiohttp = 3.8.4 needed by python3-homeassistant-2023.5.0-r0.cortexa7t2hf_neon_vfpv4 from oe-repo</font>
<font color="#C01C28">  - nothing provides python3-awesomeversion = 22.9.0 needed by python3-homeassistant-2023.5.0-r0.cortexa7t2hf_neon_vfpv4 from oe-repo</font>
<font color="#C01C28">  - nothing provides python3-lru-dict = 1.1.8 needed by python3-homeassistant-2023.5.0-r0.cortexa7t2hf_neon_vfpv4 from oe-repo</font>
<font color="#C01C28">  - nothing provides python3-requests = 2.28.2 needed by python3-homeassistant-2023.5.0-r0.cortexa7t2hf_neon_vfpv4 from oe-repo</font>
<font color="#C01C28">  - nothing provides python3-typing-extensions = 4.5.0 needed by python3-homeassistant-2023.5.0-r0.cortexa7t2hf_neon_vfpv4 from oe-repo</font>
<font color="#C01C28">(try to add &apos;--skip-broken&apos; to skip uninstallable packages)</font>

<font color="#C01C28"><b>ERROR</b></font>: <font color="#C01C28">Logfile of failure stored in: /home/tower1/yocto/mickledore/projects/homeAssistant/build/tmp/work/raspberrypi_cm3-poky-linux-gnueabi/core-image-homeassistant/1.0/temp/log.do_rootfs.5893</font>
<font color="#C01C28"><b>ERROR</b></font>: <font color="#C01C28">Task (/home/tower1/yocto/mickledore/poky/meta-homeassistant/recipes-homeassistant/images/core-image-homeassistant.bb:do_rootfs) failed with exit code &apos;1&apos;</font>
<b>NOTE</b>: Tasks Summary: Attempted 9673 tasks of which 9646 didn&apos;t need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/tower1/yocto/mickledore/poky/meta-homeassistant/recipes-homeassistant/images/core-image-homeassistant.bb:do_rootfs
Summary: There was 1 ERROR message, returning a non-zero exit code.
</pre>

**Comment by Gerry546** [comment]
Are you building a specific tag of this layer? Or is this an intermediate commit you are trying? I recommend at least to build the tags. 

The last error seems strange, and possibly unrelated, For instance, it cannot seem to find python3-pyyaml. But that recipe is provided by poky/meta/recipes-devtools/python itself in the mickledore branc, so that would mean your bblayers.conf might be misconfigured?

**Comment by bachp** [comment]
Is this issue still occuring with the latest version?

**Comment by Gerry546** [comment]
Current main needs support from a newer version `10.1.1`. So I would say no.
