### ISSUE TITLE
maturin? incorrectly names orjson .so

### ISSUE THREAD

**Issue by andred** [meta-homeassistant/meta-homeassistant#89]
When building this layer against musl, the python3-orjson .so is incorrectly named:
* orjson.cpython-311-aarch64-linux-musl.so
whereas it should be
* orjson.cpython-311-aarch64-linux-gnu.so
according to how yocto configures python3

This mismatch means that the python3 interpreter can't import orjson of course.

`<prefix>/python3-orjson/3.9.1-r0/recipe-sysroot/usr/lib/python-sysconfigdata` and `<prefix>/python3-orjson/3.9.1-r0/recipe-sysroot/usr/python-target-config/` and
```
import sysconfig
sysconfig.get_config_var('SOABI')
```
all seem to agree on the expected .cpython-311-aarch64-linux-gnu.so suffix.

The incorrect suffix is created during do_compile of python3-orjson, as that's what the generated `<prefix>/python3-orjson/3.9.1-r0/build/target/wheels/orjson-3.9.1-cp311-cp311-linux_aarch64.whl` contains.

Any ideas? (For now I'm just renaming the file as part of do_install, but of course that's not the real solution :-)

**Comment by andred** [comment]
> This is not the only package that has this, the same happens in all files

Interestingly I've not noticed this mismatch in any other packages. Are you referring to a homeassistant-image, or something else?

Anyway, I'll have a look when I get some more time

**Comment by messense** [comment]
musllinux abi is a mess, see https://github.com/pypa/auditwheel/issues/349.

On Python 3.11 and later versions `-musl` should be used, so I think yocto should change it to be better aligned with other musl based distributions like Alpine Linux.

**Comment by Gerry546** [comment]
If that is the case, then this should indeed be fixed in a wider sense and there is not a lot we can do in this layer.
